// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHAuZs3X8fp8tyVt63XVr2uvR4EL-gP0',
    appId: '1:897348520214:web:ee95eb89c3a2e7057ee837',
    messagingSenderId: '897348520214',
    projectId: 'nestbuddy-d6c82',
    authDomain: 'nestbuddy-d6c82.firebaseapp.com',
    storageBucket: 'nestbuddy-d6c82.firebasestorage.app',
    measurementId: 'G-4P7CWC1QTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5CbUvm3zKkAPud-oUks5inPhZ3uFIUX4',
    appId: '1:897348520214:android:b1989cf46b9b01797ee837',
    messagingSenderId: '897348520214',
    projectId: 'nestbuddy-d6c82',
    storageBucket: 'nestbuddy-d6c82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6inBYb_mcG3Oi-RtavUrBXYCdqO_lEDk',
    appId: '1:897348520214:ios:8e38b13fc1f85a577ee837',
    messagingSenderId: '897348520214',
    projectId: 'nestbuddy-d6c82',
    storageBucket: 'nestbuddy-d6c82.firebasestorage.app',
    iosBundleId: 'com.application.nestbuddy',
  );

}